# Generated by Django 4.2.14 on 2024-08-20 11:14

from django.db import migrations, models
import resturant.models


class Migration(migrations.Migration):

    dependencies = [
        ('resturant', '0005_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('image', models.ImageField(upload_to=resturant.models.news_image_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
