# Generated by Django 4.2.14 on 2024-08-20 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resturant', '0006_news'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name_plural': 'news'},
        ),
    ]
