# Generated by Django 4.2.14 on 2024-08-20 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resturant', '0007_alter_news_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
